// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Speciality_Metals_Back_End.SpecialityMetals_Models.GRV;

#nullable disable

namespace Speciality_Metals_Back_End.Migrations
{
    [DbContext(typeof(GRVDbContext))]
    [Migration("20241211140636_InitialCreateForGRV")]
    partial class InitialCreateForGRV
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Speciality_Metals_Back_End.SpecialityMetals_Models.GRV.GRV", b =>
                {
                    b.Property<int>("GRV_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GRV_ID"), 1L, 1);

                    b.Property<string>("GRV_Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("GRV_ID");

                    b.ToTable("GRVs");
                });
#pragma warning restore 612, 618
        }
    }
}
